apiVersion: v1
kind: Service
metadata:
  name: production
spec:
  type: ClusterIP
  selector:
    app: production
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
