---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: non-production
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./home/arjun_vk/k8s/flux/fleet-infra/clusters/my-cluster
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: non-production
  targetNamespace: default
  timeout: 3m0s
  wait: true
